In [4]:
import numpy as np
import pandas as pd

In [5]:
df_fraud = pd.read_csv('assets/fraud_data.csv')
#print(df_fraud)
#print(df_fraud.Class)
bincount = np.bincount(df_fraud.Class)
instance_of_fraud = bincount[1]/bincount[0]
print((bincount))
print(instance_of_fraud)

[21337   356]
0.016684632328818484


In [19]:
df_fraud = pd.read_csv('assets/fraud_data.csv')
#print(df_fraud)
print(df_fraud.Class)
print(df_fraud.Class.sum())
print(df_fraud.Class.sum()/len(df_fraud.Class))

0        0
1        0
2        0
3        0
4        0
        ..
21688    0
21689    0
21690    0
21691    0
21692    0
Name: Class, Length: 21693, dtype: int64
356
0.016410823768035772


In [6]:
def answer_one():
    # YOUR CODE HERE
    #raise NotImplementedError()
    df_fraud = pd.read_csv('assets/fraud_data.csv')
    bincount = np.bincount(df_fraud.Class)
    instance_of_fraud = bincount[1]/bincount[0]
    return (instance_of_fraud)
    #raise NotImplementedError()

answer_one()

0.016684632328818484

In [7]:
from sklearn.model_selection import train_test_split

df = pd.read_csv('assets/fraud_data.csv')

X = df.iloc[:,:-1]
y = df.iloc[:,-1]

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

In [5]:
from sklearn.dummy import DummyClassifier
from sklearn.metrics import recall_score
from sklearn.metrics import accuracy_score

dummy_majority = DummyClassifier(strategy = 'most_frequent').fit(X_train, y_train)
y_dummy_predictions = dummy_majority.predict(X_test)

print(y_dummy_predictions)

print(recall_score(y_test, y_dummy_predictions))
print(accuracy_score(y_test, y_dummy_predictions))


[0 0 0 ... 0 0 0]
0.0
0.9852507374631269


In [6]:
def answer_two():
    from sklearn.dummy import DummyClassifier
    from sklearn.metrics import recall_score
    from sklearn.metrics import accuracy_score

    # YOUR CODE HERE
    dummy_majority = DummyClassifier(strategy = 'most_frequent').fit(X_train, y_train)
    y_dummy_predictions = dummy_majority.predict(X_test)
    
    return (accuracy_score(y_test, y_dummy_predictions),recall_score(y_test, y_dummy_predictions))
    #raise NotImplementedError()

answer_two()

(0.9852507374631269, 0.0)

In [7]:
from sklearn.metrics import recall_score, precision_score, accuracy_score
from sklearn.svm import SVC

clf = SVC().fit(X_train, y_train)
y_predict = clf.predict(X_test)

print(accuracy_score(y_test,y_predict))
print(recall_score(y_test,y_predict))
print(precision_score(y_test,y_predict))

0.9900442477876106
0.35
0.9333333333333333


In [8]:
def answer_three():
    from sklearn.metrics import recall_score, precision_score, accuracy_score
    from sklearn.svm import SVC
    
    # YOUR CODE HERE
    clf = SVC().fit(X_train, y_train)
    y_predict = clf.predict(X_test)

    return (accuracy_score(y_test,y_predict),recall_score(y_test,y_predict),precision_score(y_test,y_predict))
    #raise NotImplementedError()

answer_three()

(0.9900442477876106, 0.35, 0.9333333333333333)

In [9]:
from sklearn.metrics import confusion_matrix
from sklearn.svm import SVC

clf_q4 = SVC(C=1e9,gamma=1e-07).fit(X_train, y_train)
y_predict4 = clf_q4.decision_function(X_test) > -220

confusion = confusion_matrix(y_test, y_predict4)


In [10]:
def answer_four():
    from sklearn.metrics import confusion_matrix
    from sklearn.svm import SVC
    
    # YOUR CODE HERE
    clf_q4 = SVC(C=1e9,gamma=1e-07).fit(X_train, y_train)
    y_predict4 = clf_q4.decision_function(X_test) > -220

    confusion = confusion_matrix(y_test, y_predict4)
    return confusion
    #raise NotImplementedError()

answer_four()

array([[5320,   24],
       [  14,   66]], dtype=int64)

In [11]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import precision_recall_curve, roc_curve, auc

clf_q5 = LogisticRegression().fit(X_train, y_train)
y_predict_q5 = clf_q5.predict(X_test)

precision, recall, thresholds = precision_recall_curve(y_test, y_predict_q5)
fpr_lr, tpr_lr, _ = roc_curve(y_test, y_predict_q5)

closest_zero = np.argmin(np.abs(thresholds))
closest_zero_p = precision[closest_zero]
closest_zero_r = recall[closest_zero]


%matplotlib inline
plt.figure()
plt.xlim([0.0, 1.01])
plt.ylim([0.0, 1.01])
plt.plot(precision, recall, label='Precision-Recall Curve')
plt.plot(closest_zero_p, closest_zero_r, 'o', markersize = 12, fillstyle = 'none', c='r', mew=3)
plt.xlabel('Precision', fontsize=16)
plt.ylabel('Recall', fontsize=16)
plt.axes().set_aspect('equal')
plt.show()

plt.figure()
plt.xlim([-0.01, 1.00])
plt.ylim([-0.01, 1.01])
plt.plot(fpr_lr, tpr_lr, lw=3, label='LogRegr ROC curve (area = {:0.2f})'.format(roc_auc_lr))
plt.xlabel('False Positive Rate', fontsize=16)
plt.ylabel('True Positive Rate', fontsize=16)
plt.title('ROC curve (1-of-10 digits classifier)', fontsize=16)
plt.legend(loc='lower right', fontsize=13)
plt.plot([0, 1], [0, 1], color='navy', lw=3, linestyle='--')
plt.axes().set_aspect('equal')
plt.show()


c:\Users\teres\anaconda3\envs\coursera\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


ImportError: DLL load failed while importing _imaging: The specified module could not be found.

In [17]:
import numpy as np

def answer_five():
    # YOUR CODE HERE

    from sklearn.linear_model import LogisticRegression
    from sklearn.metrics import precision_recall_curve, roc_curve, auc

    clf_q5 = LogisticRegression(solver='liblinear').fit(X_train, y_train)
    y_predict_q5 = clf_q5.decision_function(X_test)

    precision, recall, thresholds = precision_recall_curve(y_test, y_predict_q5)
    idx = np.where(precision == 0.75)[0][0]
    recall_q5 = recall[idx]

    fpr_lr, tpr_lr, _ = roc_curve(y_test, y_predict_q5)
    idx_fpr = np.where(np.round(fpr_lr,2) == 0.16)[0][0]
    tpr_q5 = tpr_lr[idx_fpr]

    return (recall_q5,tpr_q5)

    #raise NotImplementedError()

answer_five()

(0.825, 0.9375)

In [15]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import precision_recall_curve, roc_curve, auc
       
lr = LogisticRegression().fit(X_train, y_train)
lr_predicted = lr.predict(X_test)
precision, recall, thresholds = precision_recall_curve(y_test, lr_predicted)
fpr_lr, tpr_lr, _ = roc_curve(y_test, lr_predicted)



print(precision)

[0.01474926 0.94029851 1.        ]


c:\Users\teres\anaconda3\envs\coursera\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [18]:
import matplotlib
%matplotlib inline
        
closest_zero = np.argmin(np.abs(thresholds))
closest_zero_p = precision[closest_zero]
closest_zero_r = recall[closest_zero]
plt.figure()
plt.xlim([0.0, 1.01])
plt.ylim([0.0, 1.01])
plt.plot(precision, recall, label='Precision-Recall Curve')
plt.plot(closest_zero_p, closest_zero_r, 'o', markersize = 12, fillstyle = 'none', c='r', mew=3)
plt.xlabel('Precision', fontsize=16)
plt.ylabel('Recall', fontsize=16)
plt.axes().set_aspect('equal')
plt.show()
        
roc_auc_lr = auc(fpr_lr, tpr_lr)
plt.figure()
plt.xlim([-0.01, 1.00])
plt.ylim([-0.01, 1.01])
plt.plot(fpr_lr, tpr_lr, lw=3, label='LogRegr ROC curve (area = {:0.2f})'.format(roc_auc_lr))
plt.xlabel('False Positive Rate', fontsize=16)
plt.ylabel('True Positive Rate', fontsize=16)
plt.title('ROC Curve', fontsize=16)
plt.legend(loc='lower right', fontsize=13)
plt.plot([0, 1], [0, 1], color='navy', lw=3, linestyle='--')
plt.axes().set_aspect('equal')
plt.show()

ImportError: DLL load failed while importing _imaging: The specified module could not be found.

In [24]:
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression

clf_q6 = LogisticRegression(solver='liblinear').fit(X_train, y_train)
grid_values = {'penalty': ['11', '12'], 'C' : [0.01, 0.1, 1, 10]}

grid_clf_acc = GridSearchCV(clf_q6, param_grid = grid_values, scoring='recall')
grid_clf_acc.fit(X_train, y_train)
#y_decision_fn_scores_acc = grid_clf_acc.decision_function(X_test) 


ValueError: 
All the 40 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
20 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\teres\anaconda3\envs\coursera\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\teres\anaconda3\envs\coursera\lib\site-packages\sklearn\linear_model\_logistic.py", line 1160, in fit
    self._validate_params()
  File "c:\Users\teres\anaconda3\envs\coursera\lib\site-packages\sklearn\base.py", line 581, in _validate_params
    validate_parameter_constraints(
  File "c:\Users\teres\anaconda3\envs\coursera\lib\site-packages\sklearn\utils\_param_validation.py", line 97, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'penalty' parameter of LogisticRegression must be a str among {'l1', 'l2', 'none' (deprecated), 'elasticnet'} or None. Got '11' instead.

--------------------------------------------------------------------------------
20 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\teres\anaconda3\envs\coursera\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\teres\anaconda3\envs\coursera\lib\site-packages\sklearn\linear_model\_logistic.py", line 1160, in fit
    self._validate_params()
  File "c:\Users\teres\anaconda3\envs\coursera\lib\site-packages\sklearn\base.py", line 581, in _validate_params
    validate_parameter_constraints(
  File "c:\Users\teres\anaconda3\envs\coursera\lib\site-packages\sklearn\utils\_param_validation.py", line 97, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'penalty' parameter of LogisticRegression must be a str among {'l1', 'l2', 'none' (deprecated), 'elasticnet'} or None. Got '12' instead.


In [22]:
def answer_six():    
    from sklearn.model_selection import GridSearchCV
    from sklearn.linear_model import LogisticRegression

    lr = LogisticRegression(solver='liblinear').fit(X_train, y_train)
    grid_values = {'penalty': ['l1', 'l2'], 'C': [0.01, 0.1, 1, 10]}
    grid_clf_rec = GridSearchCV(lr, param_grid = grid_values, scoring = 'recall')
    grid_clf_rec.fit(X_train, y_train)

    print(grid_clf_rec.cv_results_)
    #print(len(np.array(grid_clf_rec.cv_results_['mean_test_score'])))
    
    return np.array([grid_clf_rec.cv_results_['mean_test_score'][x:x+2] for x in range(0, len(grid_clf_rec.cv_results_['mean_test_score']), 2)])

answer_six()

{'mean_fit_time': array([0.02275791, 0.03787613, 0.03200693, 0.06460419, 0.07123456,
       0.07586508, 0.09172564, 0.09199176]), 'std_fit_time': array([0.001303  , 0.00278389, 0.0049408 , 0.00485031, 0.01286997,
       0.01313124, 0.03285523, 0.01055277]), 'mean_score_time': array([0.00250864, 0.0024004 , 0.00200076, 0.00200057, 0.00194097,
       0.00220037, 0.00233655, 0.00233808]), 'std_score_time': array([4.87231382e-04, 4.89784628e-04, 5.30983387e-07, 0.00000000e+00,
       1.18970919e-04, 3.99947177e-04, 4.23638147e-04, 4.25604360e-04]), 'param_C': masked_array(data=[0.01, 0.01, 0.1, 0.1, 1, 1, 10, 10],
             mask=[False, False, False, False, False, False, False, False],
       fill_value='?',
            dtype=object), 'param_penalty': masked_array(data=['l1', 'l2', 'l1', 'l2', 'l1', 'l2', 'l1', 'l2'],
             mask=[False, False, False, False, False, False, False, False],
       fill_value='?',
            dtype=object), 'params': [{'C': 0.01, 'penalty': 'l1'}, {'C'

array([[0.69558442, 0.77168831],
       [0.80792208, 0.81155844],
       [0.80428571, 0.81149351],
       [0.80064935, 0.80064935]])

In [20]:
print(grid_clf_rec.cv_results_['mean_test_score'])

NameError: name 'grid_clf_rec' is not defined